#https://nid.naver.com/oauth2.0/authorize?response_type=code&client_id=SvRMXugk0nIr7rCrxnCa&redirect_uri=http://localhost:8080/auth/naver

file:
  path: C:\\skinshop\\sale\\img\\

oauth:
  naver:
    page: https://nid.naver.com/oauth2.0/authorize?response_type=code&client_id=SvRMXugk0nIr7rCrxnCa&redirect_uri=http://localhost:8080/auth/naver
    callback: http://localhost:8080/auth/naver
    key: SvRMXugk0nIr7rCrxnCa
    secret: 4eQcs9TmmL
    api:
      url: https://nid.naver.com
      token: /oauth2.0/token
      profile: https://openapi.naver.com/v1/nid/me

jwt:
  secret: joyoungjun8590@gmail.com

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: #
